name = "ai-case-checker"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"
path = ".vercel/output/static"